name: Release on main

permissions:
    contents: write # to be able to publish a GitHub release
    issues: write # to be able to comment on released issues
    pull-requests: write # to be able to comment on released pull requests
    id-token: write # to enable use of OIDC for npm provenance

on:
    push:
        branches:
            - main

# Cancel previous workflows which might still be running
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    test:
        name: Test
        runs-on: [self-hosted, ubuntu-latest-no-docker, developer-foundations]
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
                node-version: [10.x, 18.x, 20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run all tests
              run: npm test

    release:
        name: Release
        runs-on: [self-hosted, ubuntu-latest-no-docker, developer-foundations]
        needs: [test]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Release and publish
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ env.ARTIFACTORY_NPM_SECRET }}
